// Generated by CoffeeScript 1.6.3
$(function() {
  var loadBitmapImg, makeSquare,
    _this = this;
  $("#cvs1").ready(function() {
    var circle, path, queue, stage;
    stage = new createjs.Stage("cvs1");
    circle = new createjs.Shape();
    circle.graphics.beginFill("red").drawCircle(0, 0, 50);
    circle.x = 100;
    circle.y = 100;
    stage.addChild(circle);
    stage.addChild(makeSquare(300, 200));
    path = "/img/miku.jpg";
    queue = new createjs.LoadQueue(true);
    queue.addEventListener("complete", function() {
      var btm, size;
      console.log("complete!");
      btm = new createjs.Bitmap(queue.getResult("image"));
      btm.x = 300;
      size = 200;
      btm.scaleX = size / btm.image.width;
      btm.scaleY = size / btm.image.height;
      console.log(btm.scaleX);
      stage.addChild(btm);
      stage.update();
      return createjs.Tween.get(btm).to({
        x: 0,
        y: 300
      }, 3000, createjs.Ease.bounceOut).call(function() {
        return console.log("fin tween");
      });
    });
    queue.loadFile({
      id: "image",
      src: path
    });
    queue.load();
    stage.update();
    return createjs.Ticker.addEventListener("tick", stage);
  });
  makeSquare = function(x, y) {
    var square;
    if (x == null) {
      x = 200;
    }
    if (y == null) {
      y = 200;
    }
    square = new createjs.Shape();
    square.graphics.beginFill("blue").drawRect(0, 0, 100, 100);
    square.x = x;
    square.y = y;
    square.addEventListener("click", function(e) {
      console.log("image clicked");
      return $.getJSON("/common/mosaic_viewer/ajax_list", function(data) {
        return console.log(data);
      });
    });
    return square;
  };
  return loadBitmapImg = function(path, x, y) {
    var img;
    if (x == null) {
      x = 300;
    }
    if (y == null) {
      y = 200;
    }
    img = new createjs.Bitmap(path);
    img.x = x;
    img.y = y;
    console.log("makeimg");
    return img;
  };
});
