// Generated by CoffeeScript 1.6.3
var _this = this;

$("#cvs1").ready(function() {
  var circle, stage;
  stage = new createjs.Stage("cvs1");
  circle = new createjs.Shape();
  circle.graphics.beginFill("red").drawCircle(0, 0, 50);
  circle.x = 100;
  circle.y = 100;
  stage.addChild(circle);
  return stage.update();
});
