// Generated by CoffeeScript 1.6.3
$(function() {
  var makeSquare,
    _this = this;
  $("#cvs1").ready(function() {
    var circle, stage;
    stage = new createjs.Stage("cvs1");
    circle = new createjs.Shape();
    circle.graphics.beginFill("red").drawCircle(0, 0, 50);
    circle.x = 100;
    circle.y = 100;
    stage.addChild(circle);
    stage.addChild(makeSquare());
    return stage.update();
  });
  return makeSquare = function(x, y) {
    var square;
    if (x == null) {
      x = 200;
    }
    if (y == null) {
      y = 200;
    }
    square = new createjs.Shape();
    square.graphics.beginFill("blue").drawRect(0, 0, 100, 100);
    square.x = x;
    square.y = y;
    return square;
  };
});
