// Generated by CoffeeScript 1.6.3
window.onload = function() {
  var canvas, ctx;
  canvas = document.getElementById("cvs1");
  ctx = canvas.getContext('2d');
  ctx.fillStyle = "#000000";
  ctx.beginPath();
  ctx.fillRect(50, 50, 100, 100);
  console.log("here");
  return console.log("clicked aa");
};
